distributed.nanny - INFO -         Start Nanny at: 'tcp://172.20.5.184:42033'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.20.5.184:42033'
distributed.nanny - WARNING - Worker process still alive after 0 seconds, killing
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/distributed/node.py", line 173, in wait_for
    await asyncio.wait_for(future, timeout=timeout)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 440, in <module>
    go()
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 436, in go
    main()
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 422, in main
    loop.run_sync(run)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 416, in run
    await asyncio.gather(*nannies)
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/juliec/miniconda3/envs/mti_nma_viz/lib/python3.7/site-packages/distributed/node.py", line 178, in wait_for
    type(self).__name__, timeout
concurrent.futures._base.TimeoutError: Nanny failed to start in 60 seconds
